service: predict-model-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::models-56304424-ff6e-4422-ad9c-2a1731683e44/*"

functions:
  ping:
    handler: ping_handler.ping
    events:
      - http:
          path: /ping
          method: get
  predict:
    handler: predict_handler.predict
    events:
      - http:
          path: /predict
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true